# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: MyPool

steps:
- checkout:  self
  displayName: 'Checkining out repo'

- script: |
    npm install
    npx playwright install 
    npx playwright test --project=firefox
  displayName: 'Install dependencies and run playwright tests'
